/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  BMarketTakeItemHandler,
  BMarketTakeItemHandlerInterface,
} from "../../../../../contracts/private/interfaces/ITakeItemHandler.sol/BMarketTakeItemHandler";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "game",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "ItemNotTaken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "game",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "server",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "item",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "ItemTaken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "game",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "server",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "item",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "metadata",
        type: "uint256[2]",
      },
    ],
    name: "TakeItem",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212207614b6d7bf6418584a30f3f097234d967ee3ef68e4d06301deda2627b9f7e54b64736f6c63430008110033";

type BMarketTakeItemHandlerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BMarketTakeItemHandlerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BMarketTakeItemHandler__factory extends ContractFactory {
  constructor(...args: BMarketTakeItemHandlerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BMarketTakeItemHandler> {
    return super.deploy(overrides || {}) as Promise<BMarketTakeItemHandler>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): BMarketTakeItemHandler {
    return super.attach(address) as BMarketTakeItemHandler;
  }
  override connect(signer: Signer): BMarketTakeItemHandler__factory {
    return super.connect(signer) as BMarketTakeItemHandler__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BMarketTakeItemHandlerInterface {
    return new utils.Interface(_abi) as BMarketTakeItemHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BMarketTakeItemHandler {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BMarketTakeItemHandler;
  }
}
