/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as methodsSol from "./Methods.sol";
export type { methodsSol };
import type * as paramsSol from "./Params.sol";
export type { paramsSol };
import type * as templateSol from "./Template.sol";
export type { templateSol };
