/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  BMarketGiveItemHandler,
  BMarketGiveItemHandlerInterface,
} from "../../../../../contracts/private/interfaces/IGiveItemHandler.sol/BMarketGiveItemHandler";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "game",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "server",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "item",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "GiveItem",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "game",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "server",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "item",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "ItemGiven",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "game",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "ItemNotGiven",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212207e009840eb6054af828077175757b2566137e65afabbec7ae304718a7df0e2d964736f6c63430008110033";

type BMarketGiveItemHandlerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BMarketGiveItemHandlerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BMarketGiveItemHandler__factory extends ContractFactory {
  constructor(...args: BMarketGiveItemHandlerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BMarketGiveItemHandler> {
    return super.deploy(overrides || {}) as Promise<BMarketGiveItemHandler>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): BMarketGiveItemHandler {
    return super.attach(address) as BMarketGiveItemHandler;
  }
  override connect(signer: Signer): BMarketGiveItemHandler__factory {
    return super.connect(signer) as BMarketGiveItemHandler__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BMarketGiveItemHandlerInterface {
    return new utils.Interface(_abi) as BMarketGiveItemHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BMarketGiveItemHandler {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BMarketGiveItemHandler;
  }
}
