/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace AUCTIONSPARAMS {
  export type AuctionStruct = {
    owner: PromiseOrValue<string>;
    winner: PromiseOrValue<string>;
    currency: PromiseOrValue<string>;
    nftAddresses: PromiseOrValue<string>[];
    nftIds: PromiseOrValue<BigNumberish>[];
    nftAmounts: PromiseOrValue<BigNumberish>[];
    price: PromiseOrValue<BigNumberish>;
    tax: PromiseOrValue<BigNumberish>;
    currentBid: PromiseOrValue<BigNumberish>;
    nftTypes: PromiseOrValue<BigNumberish>[];
    status: PromiseOrValue<BigNumberish>;
  };

  export type AuctionStructOutput = [
    string,
    string,
    string,
    string[],
    BigNumber[],
    BigNumber[],
    BigNumber,
    BigNumber,
    BigNumber,
    number[],
    number
  ] & {
    owner: string;
    winner: string;
    currency: string;
    nftAddresses: string[];
    nftIds: BigNumber[];
    nftAmounts: BigNumber[];
    price: BigNumber;
    tax: BigNumber;
    currentBid: BigNumber;
    nftTypes: number[];
    status: number;
  };
}

export interface AUCTIONSInterface extends utils.Interface {
  functions: {
    "auctions(uint256)": FunctionFragment;
    "bid(uint256)": FunctionFragment;
    "cancel(uint256)": FunctionFragment;
    "checkItemsApproval(address,address[],uint256[],uint32[])": FunctionFragment;
    "checkTokensApproval(address,address)": FunctionFragment;
    "create(address[],uint256[],uint256[],uint32[],uint256,uint256,address)": FunctionFragment;
    "discounts()": FunctionFragment;
    "fee()": FunctionFragment;
    "finish(uint256)": FunctionFragment;
    "get(uint256)": FunctionFragment;
    "id()": FunctionFragment;
    "methods()": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "operationDiscountCosts(address,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pay(address,address,address,uint256[],uint256[],uint8)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setParams(uint256,address,address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferTokens(address,address,address[],uint256[],uint256[],uint32[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "auctions"
      | "bid"
      | "cancel"
      | "checkItemsApproval"
      | "checkTokensApproval"
      | "create"
      | "discounts"
      | "fee"
      | "finish"
      | "get"
      | "id"
      | "methods"
      | "onERC1155BatchReceived"
      | "onERC1155Received"
      | "onERC721Received"
      | "operationDiscountCosts"
      | "owner"
      | "pay"
      | "renounceOwnership"
      | "setParams"
      | "supportsInterface"
      | "transferOwnership"
      | "transferTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "auctions",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "bid",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkItemsApproval",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTokensApproval",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "create",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(functionFragment: "discounts", values?: undefined): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finish",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "get",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "id", values?: undefined): string;
  encodeFunctionData(functionFragment: "methods", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "operationDiscountCosts",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pay",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setParams",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTokens",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkItemsApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTokensApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "discounts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "finish", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "id", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "methods", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operationDiscountCosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setParams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTokens",
    data: BytesLike
  ): Result;

  events: {
    "Bid(uint256,tuple)": EventFragment;
    "Cancellation(uint256,tuple)": EventFragment;
    "Finished(uint256,tuple)": EventFragment;
    "NewAuction(uint256,tuple)": EventFragment;
    "NewPayment(address,address,address,uint256[],uint256[],uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Bid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Cancellation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Finished"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewAuction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewPayment"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface BidEventObject {
  id: BigNumber;
  auction: AUCTIONSPARAMS.AuctionStructOutput;
}
export type BidEvent = TypedEvent<
  [BigNumber, AUCTIONSPARAMS.AuctionStructOutput],
  BidEventObject
>;

export type BidEventFilter = TypedEventFilter<BidEvent>;

export interface CancellationEventObject {
  id: BigNumber;
  auction: AUCTIONSPARAMS.AuctionStructOutput;
}
export type CancellationEvent = TypedEvent<
  [BigNumber, AUCTIONSPARAMS.AuctionStructOutput],
  CancellationEventObject
>;

export type CancellationEventFilter = TypedEventFilter<CancellationEvent>;

export interface FinishedEventObject {
  id: BigNumber;
  auction: AUCTIONSPARAMS.AuctionStructOutput;
}
export type FinishedEvent = TypedEvent<
  [BigNumber, AUCTIONSPARAMS.AuctionStructOutput],
  FinishedEventObject
>;

export type FinishedEventFilter = TypedEventFilter<FinishedEvent>;

export interface NewAuctionEventObject {
  id: BigNumber;
  auction: AUCTIONSPARAMS.AuctionStructOutput;
}
export type NewAuctionEvent = TypedEvent<
  [BigNumber, AUCTIONSPARAMS.AuctionStructOutput],
  NewAuctionEventObject
>;

export type NewAuctionEventFilter = TypedEventFilter<NewAuctionEvent>;

export interface NewPaymentEventObject {
  from: string;
  to: string;
  currency: string;
  ids: BigNumber[];
  amounts: BigNumber[];
  paymentType: number;
}
export type NewPaymentEvent = TypedEvent<
  [string, string, string, BigNumber[], BigNumber[], number],
  NewPaymentEventObject
>;

export type NewPaymentEventFilter = TypedEventFilter<NewPaymentEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface AUCTIONS extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AUCTIONSInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    auctions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, BigNumber, BigNumber, number] & {
        owner: string;
        winner: string;
        currency: string;
        price: BigNumber;
        tax: BigNumber;
        currentBid: BigNumber;
        status: number;
      }
    >;

    bid(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancel(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    checkItemsApproval(
      sender: PromiseOrValue<string>,
      nftAddressArray: PromiseOrValue<string>[],
      nftTokenIdArray: PromiseOrValue<BigNumberish>[],
      nftTokenTypeArray: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[void]>;

    checkTokensApproval(
      from: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    create(
      _nftAddresses: PromiseOrValue<string>[],
      _nftIds: PromiseOrValue<BigNumberish>[],
      _nftAmounts: PromiseOrValue<BigNumberish>[],
      _nftTypes: PromiseOrValue<BigNumberish>[],
      _price: PromiseOrValue<BigNumberish>,
      _tax: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    discounts(overrides?: CallOverrides): Promise<[string]>;

    fee(overrides?: CallOverrides): Promise<[BigNumber]>;

    finish(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    get(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[AUCTIONSPARAMS.AuctionStructOutput]>;

    id(overrides?: CallOverrides): Promise<[BigNumber]>;

    methods(overrides?: CallOverrides): Promise<[string]>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    operationDiscountCosts(
      buyer: PromiseOrValue<string>,
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        discount: BigNumber;
        operationFee: BigNumber;
        operationFeeDiscount: BigNumber;
        bmarketFee: BigNumber;
        totalToPay: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pay(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      paymentType: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setParams(
      _fee: PromiseOrValue<BigNumberish>,
      _discounts: PromiseOrValue<string>,
      _methods: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferTokens(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      nftAddresses: PromiseOrValue<string>[],
      nftIds: PromiseOrValue<BigNumberish>[],
      nftAmounts: PromiseOrValue<BigNumberish>[],
      nftTypes: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  auctions(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber, BigNumber, BigNumber, number] & {
      owner: string;
      winner: string;
      currency: string;
      price: BigNumber;
      tax: BigNumber;
      currentBid: BigNumber;
      status: number;
    }
  >;

  bid(
    auctionId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancel(
    auctionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  checkItemsApproval(
    sender: PromiseOrValue<string>,
    nftAddressArray: PromiseOrValue<string>[],
    nftTokenIdArray: PromiseOrValue<BigNumberish>[],
    nftTokenTypeArray: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<void>;

  checkTokensApproval(
    from: PromiseOrValue<string>,
    currency: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  create(
    _nftAddresses: PromiseOrValue<string>[],
    _nftIds: PromiseOrValue<BigNumberish>[],
    _nftAmounts: PromiseOrValue<BigNumberish>[],
    _nftTypes: PromiseOrValue<BigNumberish>[],
    _price: PromiseOrValue<BigNumberish>,
    _tax: PromiseOrValue<BigNumberish>,
    _currency: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  discounts(overrides?: CallOverrides): Promise<string>;

  fee(overrides?: CallOverrides): Promise<BigNumber>;

  finish(
    auctionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  get(
    auctionId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<AUCTIONSPARAMS.AuctionStructOutput>;

  id(overrides?: CallOverrides): Promise<BigNumber>;

  methods(overrides?: CallOverrides): Promise<string>;

  onERC1155BatchReceived(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>[],
    arg3: PromiseOrValue<BigNumberish>[],
    arg4: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BigNumberish>,
    arg4: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  operationDiscountCosts(
    buyer: PromiseOrValue<string>,
    auctionId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      discount: BigNumber;
      operationFee: BigNumber;
      operationFeeDiscount: BigNumber;
      bmarketFee: BigNumber;
      totalToPay: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  pay(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    currency: PromiseOrValue<string>,
    ids: PromiseOrValue<BigNumberish>[],
    amounts: PromiseOrValue<BigNumberish>[],
    paymentType: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setParams(
    _fee: PromiseOrValue<BigNumberish>,
    _discounts: PromiseOrValue<string>,
    _methods: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferTokens(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    nftAddresses: PromiseOrValue<string>[],
    nftIds: PromiseOrValue<BigNumberish>[],
    nftAmounts: PromiseOrValue<BigNumberish>[],
    nftTypes: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    auctions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, BigNumber, BigNumber, number] & {
        owner: string;
        winner: string;
        currency: string;
        price: BigNumber;
        tax: BigNumber;
        currentBid: BigNumber;
        status: number;
      }
    >;

    bid(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancel(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    checkItemsApproval(
      sender: PromiseOrValue<string>,
      nftAddressArray: PromiseOrValue<string>[],
      nftTokenIdArray: PromiseOrValue<BigNumberish>[],
      nftTokenTypeArray: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    checkTokensApproval(
      from: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    create(
      _nftAddresses: PromiseOrValue<string>[],
      _nftIds: PromiseOrValue<BigNumberish>[],
      _nftAmounts: PromiseOrValue<BigNumberish>[],
      _nftTypes: PromiseOrValue<BigNumberish>[],
      _price: PromiseOrValue<BigNumberish>,
      _tax: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    discounts(overrides?: CallOverrides): Promise<string>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    finish(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    get(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<AUCTIONSPARAMS.AuctionStructOutput>;

    id(overrides?: CallOverrides): Promise<BigNumber>;

    methods(overrides?: CallOverrides): Promise<string>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    operationDiscountCosts(
      buyer: PromiseOrValue<string>,
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        discount: BigNumber;
        operationFee: BigNumber;
        operationFeeDiscount: BigNumber;
        bmarketFee: BigNumber;
        totalToPay: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    pay(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      paymentType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setParams(
      _fee: PromiseOrValue<BigNumberish>,
      _discounts: PromiseOrValue<string>,
      _methods: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferTokens(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      nftAddresses: PromiseOrValue<string>[],
      nftIds: PromiseOrValue<BigNumberish>[],
      nftAmounts: PromiseOrValue<BigNumberish>[],
      nftTypes: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Bid(uint256,tuple)"(
      id?: PromiseOrValue<BigNumberish> | null,
      auction?: null
    ): BidEventFilter;
    Bid(
      id?: PromiseOrValue<BigNumberish> | null,
      auction?: null
    ): BidEventFilter;

    "Cancellation(uint256,tuple)"(
      id?: PromiseOrValue<BigNumberish> | null,
      auction?: null
    ): CancellationEventFilter;
    Cancellation(
      id?: PromiseOrValue<BigNumberish> | null,
      auction?: null
    ): CancellationEventFilter;

    "Finished(uint256,tuple)"(id?: null, auction?: null): FinishedEventFilter;
    Finished(id?: null, auction?: null): FinishedEventFilter;

    "NewAuction(uint256,tuple)"(
      id?: PromiseOrValue<BigNumberish> | null,
      auction?: null
    ): NewAuctionEventFilter;
    NewAuction(
      id?: PromiseOrValue<BigNumberish> | null,
      auction?: null
    ): NewAuctionEventFilter;

    "NewPayment(address,address,address,uint256[],uint256[],uint8)"(
      from?: null,
      to?: null,
      currency?: null,
      ids?: null,
      amounts?: null,
      paymentType?: null
    ): NewPaymentEventFilter;
    NewPayment(
      from?: null,
      to?: null,
      currency?: null,
      ids?: null,
      amounts?: null,
      paymentType?: null
    ): NewPaymentEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    auctions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bid(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancel(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    checkItemsApproval(
      sender: PromiseOrValue<string>,
      nftAddressArray: PromiseOrValue<string>[],
      nftTokenIdArray: PromiseOrValue<BigNumberish>[],
      nftTokenTypeArray: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkTokensApproval(
      from: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    create(
      _nftAddresses: PromiseOrValue<string>[],
      _nftIds: PromiseOrValue<BigNumberish>[],
      _nftAmounts: PromiseOrValue<BigNumberish>[],
      _nftTypes: PromiseOrValue<BigNumberish>[],
      _price: PromiseOrValue<BigNumberish>,
      _tax: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    discounts(overrides?: CallOverrides): Promise<BigNumber>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    finish(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    get(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    id(overrides?: CallOverrides): Promise<BigNumber>;

    methods(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    operationDiscountCosts(
      buyer: PromiseOrValue<string>,
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pay(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      paymentType: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setParams(
      _fee: PromiseOrValue<BigNumberish>,
      _discounts: PromiseOrValue<string>,
      _methods: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferTokens(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      nftAddresses: PromiseOrValue<string>[],
      nftIds: PromiseOrValue<BigNumberish>[],
      nftAmounts: PromiseOrValue<BigNumberish>[],
      nftTypes: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    auctions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bid(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancel(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    checkItemsApproval(
      sender: PromiseOrValue<string>,
      nftAddressArray: PromiseOrValue<string>[],
      nftTokenIdArray: PromiseOrValue<BigNumberish>[],
      nftTokenTypeArray: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkTokensApproval(
      from: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    create(
      _nftAddresses: PromiseOrValue<string>[],
      _nftIds: PromiseOrValue<BigNumberish>[],
      _nftAmounts: PromiseOrValue<BigNumberish>[],
      _nftTypes: PromiseOrValue<BigNumberish>[],
      _price: PromiseOrValue<BigNumberish>,
      _tax: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    discounts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    finish(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    get(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    id(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    methods(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    operationDiscountCosts(
      buyer: PromiseOrValue<string>,
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pay(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      paymentType: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setParams(
      _fee: PromiseOrValue<BigNumberish>,
      _discounts: PromiseOrValue<string>,
      _methods: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferTokens(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      nftAddresses: PromiseOrValue<string>[],
      nftIds: PromiseOrValue<BigNumberish>[],
      nftAmounts: PromiseOrValue<BigNumberish>[],
      nftTypes: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
