/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iGamesSol from "./IGames.sol";
export type { iGamesSol };
import type * as iGiveItemHandlerSol from "./IGiveItemHandler.sol";
export type { iGiveItemHandlerSol };
import type * as iRefundItemHandlerSol from "./IRefundItemHandler.sol";
export type { iRefundItemHandlerSol };
import type * as iTakeItemHandlerSol from "./ITakeItemHandler.sol";
export type { iTakeItemHandlerSol };
import type * as iUsersSol from "./IUsers.sol";
export type { iUsersSol };
