/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as methodsSol from "./Methods.sol";
export * as paramsSol from "./Params.sol";
export * as templateSol from "./Template.sol";
