/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace RENTSPARAMS {
  export type RentStruct = {
    owner: PromiseOrValue<string>;
    currency: PromiseOrValue<string>;
    client: PromiseOrValue<string>;
    nftAddresses: PromiseOrValue<string>[];
    nftIds: PromiseOrValue<BigNumberish>[];
    nftAmounts: PromiseOrValue<BigNumberish>[];
    returningTime: PromiseOrValue<BigNumberish>;
    valability: PromiseOrValue<BigNumberish>;
    expiration: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
    fee: PromiseOrValue<BigNumberish>;
    nftTypes: PromiseOrValue<BigNumberish>[];
    status: PromiseOrValue<BigNumberish>;
  };

  export type RentStructOutput = [
    string,
    string,
    string,
    string[],
    BigNumber[],
    BigNumber[],
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number[],
    number
  ] & {
    owner: string;
    currency: string;
    client: string;
    nftAddresses: string[];
    nftIds: BigNumber[];
    nftAmounts: BigNumber[];
    returningTime: BigNumber;
    valability: BigNumber;
    expiration: BigNumber;
    price: BigNumber;
    fee: BigNumber;
    nftTypes: number[];
    status: number;
  };
}

export interface RENTSInterface extends utils.Interface {
  functions: {
    "cancel(uint256)": FunctionFragment;
    "checkItemsApproval(address,address[],uint256[],uint32[])": FunctionFragment;
    "checkTokensApproval(address,address)": FunctionFragment;
    "create(address[],uint256[],uint256[],uint32[],uint256,uint256,uint256,address)": FunctionFragment;
    "discounts()": FunctionFragment;
    "fee()": FunctionFragment;
    "finish(uint256)": FunctionFragment;
    "get(uint256)": FunctionFragment;
    "id()": FunctionFragment;
    "methods()": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "operationDiscountCosts(address,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pay(address,address,address,uint256[],uint256[],uint8)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "rent(uint256)": FunctionFragment;
    "rents(uint256)": FunctionFragment;
    "setParams(uint256,address,address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "terminate(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferTokens(address,address,address[],uint256[],uint256[],uint32[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cancel"
      | "checkItemsApproval"
      | "checkTokensApproval"
      | "create"
      | "discounts"
      | "fee"
      | "finish"
      | "get"
      | "id"
      | "methods"
      | "onERC1155BatchReceived"
      | "onERC1155Received"
      | "onERC721Received"
      | "operationDiscountCosts"
      | "owner"
      | "pay"
      | "renounceOwnership"
      | "rent"
      | "rents"
      | "setParams"
      | "supportsInterface"
      | "terminate"
      | "transferOwnership"
      | "transferTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancel",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkItemsApproval",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTokensApproval",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "create",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(functionFragment: "discounts", values?: undefined): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finish",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "get",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "id", values?: undefined): string;
  encodeFunctionData(functionFragment: "methods", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "operationDiscountCosts",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pay",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rent",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "rents",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setParams",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "terminate",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTokens",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkItemsApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTokensApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "discounts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "finish", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "id", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "methods", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operationDiscountCosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setParams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "terminate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTokens",
    data: BytesLike
  ): Result;

  events: {
    "NewPayment(address,address,address,uint256[],uint256[],uint8)": EventFragment;
    "NewRent(uint256,tuple)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RentCancelled(uint256,tuple)": EventFragment;
    "RentDone(uint256,tuple)": EventFragment;
    "RentOngoing(uint256,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewPayment"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewRent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RentCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RentDone"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RentOngoing"): EventFragment;
}

export interface NewPaymentEventObject {
  from: string;
  to: string;
  currency: string;
  ids: BigNumber[];
  amounts: BigNumber[];
  paymentType: number;
}
export type NewPaymentEvent = TypedEvent<
  [string, string, string, BigNumber[], BigNumber[], number],
  NewPaymentEventObject
>;

export type NewPaymentEventFilter = TypedEventFilter<NewPaymentEvent>;

export interface NewRentEventObject {
  id: BigNumber;
  rent: RENTSPARAMS.RentStructOutput;
}
export type NewRentEvent = TypedEvent<
  [BigNumber, RENTSPARAMS.RentStructOutput],
  NewRentEventObject
>;

export type NewRentEventFilter = TypedEventFilter<NewRentEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RentCancelledEventObject {
  id: BigNumber;
  rent: RENTSPARAMS.RentStructOutput;
}
export type RentCancelledEvent = TypedEvent<
  [BigNumber, RENTSPARAMS.RentStructOutput],
  RentCancelledEventObject
>;

export type RentCancelledEventFilter = TypedEventFilter<RentCancelledEvent>;

export interface RentDoneEventObject {
  id: BigNumber;
  rent: RENTSPARAMS.RentStructOutput;
}
export type RentDoneEvent = TypedEvent<
  [BigNumber, RENTSPARAMS.RentStructOutput],
  RentDoneEventObject
>;

export type RentDoneEventFilter = TypedEventFilter<RentDoneEvent>;

export interface RentOngoingEventObject {
  id: BigNumber;
  rent: RENTSPARAMS.RentStructOutput;
}
export type RentOngoingEvent = TypedEvent<
  [BigNumber, RENTSPARAMS.RentStructOutput],
  RentOngoingEventObject
>;

export type RentOngoingEventFilter = TypedEventFilter<RentOngoingEvent>;

export interface RENTS extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RENTSInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancel(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    checkItemsApproval(
      sender: PromiseOrValue<string>,
      nftAddressArray: PromiseOrValue<string>[],
      nftTokenIdArray: PromiseOrValue<BigNumberish>[],
      nftTokenTypeArray: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[void]>;

    checkTokensApproval(
      from: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    create(
      _nftAddresses: PromiseOrValue<string>[],
      _nftIds: PromiseOrValue<BigNumberish>[],
      _nftAmounts: PromiseOrValue<BigNumberish>[],
      _nftTypes: PromiseOrValue<BigNumberish>[],
      _valability: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _fee: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    discounts(overrides?: CallOverrides): Promise<[string]>;

    fee(overrides?: CallOverrides): Promise<[BigNumber]>;

    finish(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    get(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[RENTSPARAMS.RentStructOutput]>;

    id(overrides?: CallOverrides): Promise<[BigNumber]>;

    methods(overrides?: CallOverrides): Promise<[string]>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    operationDiscountCosts(
      buyer: PromiseOrValue<string>,
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        discount: BigNumber;
        operationFee: BigNumber;
        operationFeeDiscount: BigNumber;
        bmarketFee: BigNumber;
        totalToPay: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pay(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      paymentType: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rent(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rents(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        owner: string;
        currency: string;
        client: string;
        returningTime: BigNumber;
        valability: BigNumber;
        expiration: BigNumber;
        price: BigNumber;
        fee: BigNumber;
        status: number;
      }
    >;

    setParams(
      _fee: PromiseOrValue<BigNumberish>,
      _discounts: PromiseOrValue<string>,
      _methods: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    terminate(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferTokens(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      nftAddresses: PromiseOrValue<string>[],
      nftIds: PromiseOrValue<BigNumberish>[],
      nftAmounts: PromiseOrValue<BigNumberish>[],
      nftTypes: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  cancel(
    rentId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  checkItemsApproval(
    sender: PromiseOrValue<string>,
    nftAddressArray: PromiseOrValue<string>[],
    nftTokenIdArray: PromiseOrValue<BigNumberish>[],
    nftTokenTypeArray: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<void>;

  checkTokensApproval(
    from: PromiseOrValue<string>,
    currency: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  create(
    _nftAddresses: PromiseOrValue<string>[],
    _nftIds: PromiseOrValue<BigNumberish>[],
    _nftAmounts: PromiseOrValue<BigNumberish>[],
    _nftTypes: PromiseOrValue<BigNumberish>[],
    _valability: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    _fee: PromiseOrValue<BigNumberish>,
    _currency: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  discounts(overrides?: CallOverrides): Promise<string>;

  fee(overrides?: CallOverrides): Promise<BigNumber>;

  finish(
    rentId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  get(
    rentId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<RENTSPARAMS.RentStructOutput>;

  id(overrides?: CallOverrides): Promise<BigNumber>;

  methods(overrides?: CallOverrides): Promise<string>;

  onERC1155BatchReceived(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>[],
    arg3: PromiseOrValue<BigNumberish>[],
    arg4: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BigNumberish>,
    arg4: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  operationDiscountCosts(
    buyer: PromiseOrValue<string>,
    rentId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      discount: BigNumber;
      operationFee: BigNumber;
      operationFeeDiscount: BigNumber;
      bmarketFee: BigNumber;
      totalToPay: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  pay(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    currency: PromiseOrValue<string>,
    ids: PromiseOrValue<BigNumberish>[],
    amounts: PromiseOrValue<BigNumberish>[],
    paymentType: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rent(
    rentId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rents(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      number
    ] & {
      owner: string;
      currency: string;
      client: string;
      returningTime: BigNumber;
      valability: BigNumber;
      expiration: BigNumber;
      price: BigNumber;
      fee: BigNumber;
      status: number;
    }
  >;

  setParams(
    _fee: PromiseOrValue<BigNumberish>,
    _discounts: PromiseOrValue<string>,
    _methods: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  terminate(
    rentId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferTokens(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    nftAddresses: PromiseOrValue<string>[],
    nftIds: PromiseOrValue<BigNumberish>[],
    nftAmounts: PromiseOrValue<BigNumberish>[],
    nftTypes: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cancel(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    checkItemsApproval(
      sender: PromiseOrValue<string>,
      nftAddressArray: PromiseOrValue<string>[],
      nftTokenIdArray: PromiseOrValue<BigNumberish>[],
      nftTokenTypeArray: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    checkTokensApproval(
      from: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    create(
      _nftAddresses: PromiseOrValue<string>[],
      _nftIds: PromiseOrValue<BigNumberish>[],
      _nftAmounts: PromiseOrValue<BigNumberish>[],
      _nftTypes: PromiseOrValue<BigNumberish>[],
      _valability: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _fee: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    discounts(overrides?: CallOverrides): Promise<string>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    finish(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    get(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<RENTSPARAMS.RentStructOutput>;

    id(overrides?: CallOverrides): Promise<BigNumber>;

    methods(overrides?: CallOverrides): Promise<string>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    operationDiscountCosts(
      buyer: PromiseOrValue<string>,
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        discount: BigNumber;
        operationFee: BigNumber;
        operationFeeDiscount: BigNumber;
        bmarketFee: BigNumber;
        totalToPay: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    pay(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      paymentType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    rent(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    rents(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        owner: string;
        currency: string;
        client: string;
        returningTime: BigNumber;
        valability: BigNumber;
        expiration: BigNumber;
        price: BigNumber;
        fee: BigNumber;
        status: number;
      }
    >;

    setParams(
      _fee: PromiseOrValue<BigNumberish>,
      _discounts: PromiseOrValue<string>,
      _methods: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    terminate(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferTokens(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      nftAddresses: PromiseOrValue<string>[],
      nftIds: PromiseOrValue<BigNumberish>[],
      nftAmounts: PromiseOrValue<BigNumberish>[],
      nftTypes: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "NewPayment(address,address,address,uint256[],uint256[],uint8)"(
      from?: null,
      to?: null,
      currency?: null,
      ids?: null,
      amounts?: null,
      paymentType?: null
    ): NewPaymentEventFilter;
    NewPayment(
      from?: null,
      to?: null,
      currency?: null,
      ids?: null,
      amounts?: null,
      paymentType?: null
    ): NewPaymentEventFilter;

    "NewRent(uint256,tuple)"(
      id?: PromiseOrValue<BigNumberish> | null,
      rent?: null
    ): NewRentEventFilter;
    NewRent(
      id?: PromiseOrValue<BigNumberish> | null,
      rent?: null
    ): NewRentEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RentCancelled(uint256,tuple)"(
      id?: PromiseOrValue<BigNumberish> | null,
      rent?: null
    ): RentCancelledEventFilter;
    RentCancelled(
      id?: PromiseOrValue<BigNumberish> | null,
      rent?: null
    ): RentCancelledEventFilter;

    "RentDone(uint256,tuple)"(
      id?: PromiseOrValue<BigNumberish> | null,
      rent?: null
    ): RentDoneEventFilter;
    RentDone(
      id?: PromiseOrValue<BigNumberish> | null,
      rent?: null
    ): RentDoneEventFilter;

    "RentOngoing(uint256,tuple)"(
      id?: PromiseOrValue<BigNumberish> | null,
      rent?: null
    ): RentOngoingEventFilter;
    RentOngoing(
      id?: PromiseOrValue<BigNumberish> | null,
      rent?: null
    ): RentOngoingEventFilter;
  };

  estimateGas: {
    cancel(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    checkItemsApproval(
      sender: PromiseOrValue<string>,
      nftAddressArray: PromiseOrValue<string>[],
      nftTokenIdArray: PromiseOrValue<BigNumberish>[],
      nftTokenTypeArray: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkTokensApproval(
      from: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    create(
      _nftAddresses: PromiseOrValue<string>[],
      _nftIds: PromiseOrValue<BigNumberish>[],
      _nftAmounts: PromiseOrValue<BigNumberish>[],
      _nftTypes: PromiseOrValue<BigNumberish>[],
      _valability: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _fee: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    discounts(overrides?: CallOverrides): Promise<BigNumber>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    finish(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    get(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    id(overrides?: CallOverrides): Promise<BigNumber>;

    methods(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    operationDiscountCosts(
      buyer: PromiseOrValue<string>,
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pay(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      paymentType: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rent(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rents(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setParams(
      _fee: PromiseOrValue<BigNumberish>,
      _discounts: PromiseOrValue<string>,
      _methods: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    terminate(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferTokens(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      nftAddresses: PromiseOrValue<string>[],
      nftIds: PromiseOrValue<BigNumberish>[],
      nftAmounts: PromiseOrValue<BigNumberish>[],
      nftTypes: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cancel(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    checkItemsApproval(
      sender: PromiseOrValue<string>,
      nftAddressArray: PromiseOrValue<string>[],
      nftTokenIdArray: PromiseOrValue<BigNumberish>[],
      nftTokenTypeArray: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkTokensApproval(
      from: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    create(
      _nftAddresses: PromiseOrValue<string>[],
      _nftIds: PromiseOrValue<BigNumberish>[],
      _nftAmounts: PromiseOrValue<BigNumberish>[],
      _nftTypes: PromiseOrValue<BigNumberish>[],
      _valability: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _fee: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    discounts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    finish(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    get(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    id(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    methods(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    operationDiscountCosts(
      buyer: PromiseOrValue<string>,
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pay(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      paymentType: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rent(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rents(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setParams(
      _fee: PromiseOrValue<BigNumberish>,
      _discounts: PromiseOrValue<string>,
      _methods: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    terminate(
      rentId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferTokens(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      nftAddresses: PromiseOrValue<string>[],
      nftIds: PromiseOrValue<BigNumberish>[],
      nftAmounts: PromiseOrValue<BigNumberish>[],
      nftTypes: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
