/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as auctionsSol from "./Auctions.sol";
export * as auctionsCompanySol from "./AuctionsCompany.sol";
export * as exchangesSol from "./Exchanges.sol";
export * as gamesSol from "./Games.sol";
export * as itemBetsSol from "./ItemBets.sol";
export * as lotteriesSol from "./Lotteries.sol";
export * as rentsSol from "./Rents.sol";
export * as rentsCompanySol from "./RentsCompany.sol";
export * as salesSol from "./Sales.sol";
export * as salesCompanySol from "./SalesCompany.sol";
export * as storageSol from "./Storage.sol";
export * as usersSol from "./Users.sol";
export * as interfaces from "./interfaces";
